#
EXAMPLES =  01_simple.fl 02_example.fl 03_example.fl 04_example.fl \
	    05_example.fl 06_example.fl 07_example.fl 08_example.fl

install: $(EXAMPLES)
	-@mkdir ../../../doc/hfl_examples
	/bin/cp $(EXAMPLES) ../../../doc/hfl_examples

clean:
	-@rm ../../../doc/hfl_examples

